### ISSUE TITLE
Incorrect answered user association in the report

### ISSUE THREAD

**Issue by ugoviti** [odoopbx/addons#11]
Hi,

first of all thank you for this great odoo integration, moreover I'm glad you started using izpbx as official PBX engine ;)

I'm writing this issue because I'm experiencing only a little drawback in the call history reports when the call is answered from a Queue.

let's me explain:

If an incoming call enter a queue with ring strategy "all", the call is marked answered always from the latest number that is ringing.

I attached an image explaining the problem.

In this example the call coming from an external number was really answered from **EXT-201**, but the report is wrong because marked answered from **EXT-200** (that's only the first number in the ringing list)

![image](https://user-images.githubusercontent.com/11528563/204149550-1ed76739-0d9e-4111-9afc-e0ab7017627b.png)

![image](https://user-images.githubusercontent.com/11528563/204149206-25a70b03-a96e-465e-81ec-8ad22a2fc091.png)

As you can see, the 201 is the only extension with State **Up**, so this is the extension that answered that call.

Thank you in advance for the support, let's me know if you need other info.

Kind Regards

**Comment by litnialex** [comment]
Hello @ugoviti !

First of all let me say you many thanks for the izpbx image! I had an Idea about contacting you and letting know about our Odoo integration project and I feel so amaized that you found it yourself!

I confirm the issue. I think we should set "Called user" upon Newstate state:UP event, and leave "called users" to be filled upon each Newchannel, as it is now. May be even rename "Called user" to "Answered user", @litnimax what you think?

I'll update this issue with corresponding commit soon...

**Comment by litnimax** [comment]
Hi all!
Alex I agree that Answered User is more correct name.
Please make it as a pre-migrate.py scrip to rename the column.
```
from odoo.tools.sql import rename_column


def migrate(cr, version):
    rename_column(cr, 'asterisk_plus_call', 'called_user', 'answer_user')
```

@ugoviti, can you please contact me on telegram @litmax to discuss some ideas? ;-)

**Comment by litnialex** [comment]
Hi @ugoviti!

You may check https://github.com/odoopbx/addons/tree/fix_11

We will merge it into 15.0 branch after additional testing..

**Comment by litnialex** [comment]
@ugoviti fixed, closing the issue
