### ISSUE TITLE
No matching sls found for 'agent' in env 'base'

### ISSUE THREAD

**Issue by esakarya** [odoopbx/addons#9]
I'm trying to install on odoo v15 running virtua-env
I manually installed the asterisk server
Activate env as in the document,
pip3 install odoopbx
I ran the command. installed in env

next step when i run the command

I get the following error
No matching sls found for 'agent' in env 'base'

**Comment by esakarya** [comment]
i am on ubuntu 20 lts, and i am try standalone installationnot dockerbase

**Comment by esakarya** [comment]
For a standalone installation, you need to add more salt-related setup steps to the document.

**Comment by esakarya** [comment]
I install https://github.com/odoopbx/agent manually i changed master repo to 
file_roots:
  base:
    - /srv/salt
and now i am getting following error

Reason: 'x509' __virtual__ returned False: Could not load x509 state: m2crypto unavailable

**Comment by esakarya** [comment]
Ok fixed this step also. error now
i create one /etc/asterisk/manager_custom.conf
and i added your defaults.
and /etc/salt/auth is there. included odoo
when i try try setup server or minion ping at odoo i am getting following error.

No job ID was returned. Check Minion ID!

you need really one of clean and detailed installation document.....

**Comment by esakarya** [comment]
i am almost fnish the setup last error 
pepper.exceptions.PepperException: Authentication denied
everythink seems correct added odoo user to auth  file etc. what can be ?

**Comment by litnimax** [comment]
Hi.
That means you have an issue with /etc/salt/auth file.
I would suggest putting the defaults there and setting back the defaults in Odoo in PBX -> Settings -> Salt tab.
User: odoo
pass: odoo
/etc/salt/auth:
odoo|0a8f125a3f41f36c0507203a63cde9ad

**Comment by litnimax** [comment]
> salt-call state.apply full 

Really there is an issue in the docs.
The correct one is:

salt-call --local state.highstate

Currently you have to download the agent from the repo described here:
https://github.com/odoopbx/agent

Docs also fixed - https://github.com/odoopbx/docs/commit/0ef7100435f01684c1bc2ce204d46abf4a89d3ee

Thanks for reporting.

P.S. You did not have to manually install salt as it's installed by the Agent.

**Comment by esakarya** [comment]
Wolaaaaa ! pings begin worked. thank you. 
odoo|0a8f125a3f41f36c0507203a63cde9ad

**Comment by litnimax** [comment]
If you like our work you can give us some energy here - https://www.patreon.com/odoopbx
It can be a one time donation or (better) a monthly refill!
Thanks!

**Comment by esakarya** [comment]
Yes i told before we will still we cant run asteriks properly.
Where can i setup now sips and queues?

**Comment by litnimax** [comment]
In PBX -> Settings -> Files.
Currently Asterisk Plus does not have UI for managing SIP or Queues.
Also this question is out of scope of github tickets.
We are going to run a forum soon where you can get community assistance  on PBX issues.
Also we offer commercial PBX support services.
You can send your request at odoopbx.com.
Closing the tiket.
